### PR TITLE
Add roda-mailer_ext and roda-mailer_preview plugins

### PR DESCRIPTION
**Pull request by adam12**

### CODE REVIEW

**Comment by jeremyevans** [comment]
Looks good, thanks!

**Comment by jeremyevans** [comment]
Actually, the change should be made in the main repository in the www folder, not directly to the gh_pages branch (which is wiped and regenerated from templates/rdoc during the release process.

**Comment by adam12** [comment]
I didn't realize that. Let me figure out if I can still use this PR or if it makes sense closing and re-creating it.

**Comment by adam12** [comment]
Closing in favour of #109

**Pull request closed without merging**
