### PR TITLE
Use STATUS_WITH_NO_ENTITY_BODY in finish instead of hardcoded ints.

### PR DESCRIPTION
**Pull request by celsworth**
Rack::Utils has a Set available with this list of integers in, and checking a Set for inclusion should be faster than all the comparisons.

Just an exploratory PR really to see what you think :)

I did also wonder whether it was worth `dup`ing and `freeze`ing it to a local constant?

### CODE REVIEW

**Comment by celsworth** [comment]
Actually, upon further testing with some benchmarks, this really doesn't seem to save much if any time:

```ruby
require 'benchmark'
require 'set'

set = Set.new(100..199) << 204 << 205 << 304
fset = set.dup.freeze
t = 304

Benchmark.bm do |bm|
  bm.report do
    100000000.times do
      fset.include?(t)
    end
  end

  bm.report do
    100000000.times do
      set.include?(t)
    end
  end

  bm.report do
    100000000.times do
      if (t >= 100 && t <= 199) || t == 204 || t == 205 || t == 304
      end
    end
  end
end
```

```
       user     system      total        real
   5.880000   0.000000   5.880000 (  5.878768)
   5.810000   0.000000   5.810000 (  5.815571)
   6.240000   0.000000   6.240000 (  6.234221)
```

So it's more down to style choice, feel free to close if you like :)

**Comment by TiagoCardoso1983** [comment]
the first and second example are the same, the lookup is not influenced by the object being frozen or not. The difference of the 3rd in terms of performance is due to it using 4 O(1) rubyspace calls (`== || == || == || ==)` against 1 O(N) rubyspace call (`include?`) which is performed mostly in C. As stated in the comment earlier today, this case could be micro-optimized for the most common cases. try this as well:

```
bm.report do
    100000000.times do
      if t == 304 || t == 204 || t == 205 || (t >= 100 && t <= 199)
      end
    end
  end
```

in the benchmark.

**Comment by celsworth** [comment]
Yeah that is a lot better, almost twice as fast for the 304 case. I'll close this PR, it doesn't seem to add any value. If anything the hardcoded ints could be rearranged but the order in which to do so, I'll leave to jeremy :)

**Comment by jeremyevans** [comment]
@TiagoCardoso1983  I added commit b33c28ef56df86986930acbb42a3094825693b92 that uses your approach, as well as an additional optimization.

**Pull request closed without merging**
