### PR TITLE
Support pretty URLs (aka html index files)

### PR DESCRIPTION
**Pull request by jaredcwhite**
This new opt-in feature for the public plugin allows "pretty URLs" to work, aka

```
plugin :public, :pretty_urls=>true
```

makes this work:

```
/path/to/file => /path/to/file.html
/another/path => /another/path/index.html
```

All other file requests should work normally.

This is upstreamed from a [monkeypatch for the Bridgetown static site generator](https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/rack/static_indexes.rb).

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch.  Unfortunately, I don't think this is a good fit for inclusion in Roda, at least not as part of the public plugin.  Hard coding the `.html` file extension and the fact that this checks for `index.html` under the directory before the `.html` file may make sense in Bridgetown, but I don't think they are generic enough for inclusion in Roda.

Now, I do want it to be easy for Bridgetown to build what it needs on top of Roda, so I'll certainly consider adding extensions points if needed.  In this case, I don't think an extension point is needed, as you can already override `public_path_segments` and call `super`, then add use the code you have.

This could be built as a separate Roda plugin that requires the public plugin and overrides `public_path_segments`.  That's probably a better way to handle it, as then only the people who want the feature need to pay the cost of loading it.  I could consider such a plugin for inclusion in Roda if there is community support for it.  If you would like to go that route, please ask on the Google Group and see if there is community support for the idea.  We could even make it more generic by supporting a configurable file extension and order of lookup (file first or directory index first).

**Comment by jaredcwhite** [comment]
@jeremyevans I don't think it makes sense as a separate plugin. Most configurations of any web server I've ever seen which serves a folder tree to the public supports index files and extensionless HTML paths. I'm not suggesting it makes sense as a default, but as a backwards-compatible feature in Roda I would _expect_ the public plugin to support index files. Making it support more than just `.html` (for example `.htm`) seems reasonable, as would controlling the file vs. directory order. (I'm not sure which "wins" on Apache, Nginx, etc. for example). I'd be happy to add those to the PR.

**Comment by jeremyevans** [comment]
You'll find that there are many plugins that ship with Roda that build on other plugins that ship with Roda to add features.  That's just how things are done in Roda.  When you include features like this in the public plugin, that only a small percentage of people will use, you are making everyone that uses the public plugin pay the cost of it, which goes against Roda's philosophy.  So if you want this in Roda, it will have to be as a separate plugin that loads the public plugin as a dependency.

**Comment by jaredcwhite** [comment]
OK, thanks for the clarification there. I appreciate Roda's philosophy around performance and keeping things lean. I'll work on extracting out to a separate plugin.

**Pull request closed without merging**
