### PR TITLE
Remove Content-Type and Content-Length headers on 204/205/304 responses.

### LINKED ISSUE #101: halt plugin: 204 not properly handled
I'm using roda with halt plugin. For the delete route case I wanted to reply with 204 status code, so I have:

```ruby
  @resource.destroy
  r.halt 204
```

rack breaks with `Rack::Lint::LintError: Content-Type header found in 204 response, not allowed`. This seems to be due to roda, which by default sets the response default headers and the `Content-Type`. Roda should detect if the status of the response is already set, and if so, only set Content-Type when it's allowed. [List of status codes is here](https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L5799). [This is where roda is setting them](https://github.com/jeremyevans/roda/blob/master/lib/roda.rb#L936).

### PR DESCRIPTION
**Pull request by celsworth**
Fixes #101.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Looks good, thanks for taking care of this quickly!

**Comment by celsworth** [comment]
It  has already been improved by Jeremy after he merged it, the array is no longer used.

**Comment by TiagoCardoso1983** [comment]
I've seen it, looks much better, thx. @jeremyevans , this might sound like a needless micro-optimization, but wouldn't it make sense to move the most common conditionals forward? the `100..199` case is the first conditional in the critical path, but it's very rarely used. Would it make sense to move the 304 and 204 conditionals to the left?

**Comment by celsworth** [comment]
If none of them match then they still all need to be checked whichever order they're in.

So unless you're mostly serving 204 responses changing the order won't make much difference I think.

**Comment by celsworth** [comment]
I'll see if jeremy will accept a PR to use that `Set` already in Rack.. as you say it's already available.

**Comment by TiagoCardoso1983** [comment]
@celsworth I don't agree, most requests processed by ruby frameworks have a body, therefore will skip the conditionals. And I'd argue that the next most common scenario is 304 (etag plugins), then 204. 

Regarding Rack solution adoption, this one seems more correct, i.e. it requires less pre-allocation, I'd be more for rack adopting this than the other way round.

**Pull request merged**
