### PR TITLE
Change README, add Summary and Roda logo

### PR DESCRIPTION
**Pull request by henrique-ft**
Hello, these changes can make the repository much more attractive to new users and also improve the readability of the README, making it easier to find information.

Hope it gets merged, thanks!

Screenshot from 2022-10-08 13-35-00

### CODE REVIEW

**Comment by jeremyevans** [comment]
I prefer managing documentation in rdoc format.  I'm not opposed to the other changes, so if you can add them while keeping the documentation in rdoc format, I could accept that.  Note that syntax highlighting is already present, just not on GitHub (https://roda.jeremyevans.net/rdoc/files/README_rdoc.html).  So I think you would only need to add a summary section with links, and the logo.

**Comment by henrique-ft** [comment]
> I prefer managing documentation in rdoc format. I'm not opposed to the other changes, so if you can add them while keeping the documentation in rdoc format, I could accept that. Note that syntax highlighting is already present, just not on GitHub (https://roda.jeremyevans.net/rdoc/files/README_rdoc.html). So I think you would only need to add a summary section with links, and the logo.

Nice! done.

**Comment by jeremyevans** [comment]
Thanks, squash merged as 3eff61542af58d40ab617d12a766d5d6d641dfef

**Comment by janko** [comment]
FYI, GitHub now automatically generates a table of contents from your README markdown.

Screenshot 2022-10-09 at 11 03 17

**Pull request closed without merging**
