### PR TITLE
Split roda.rb into multiple files

### PR DESCRIPTION
**Pull request by janko**
### Rationale

From my perspective, there are several advantages to keeping the base functionality all inside `lib/roda.rb`:

* the base functionality can be just another plugin
* you have everything you need inside a single file (like Sinatra)

However, I feel that the base functionality is now large enough to benefit from splitting into multiple files. In my opinion it makes code navigation easier as it allows one to focus only on a single class at a time.

### Proposal

My proposal is to move classes into separate files:

| Class                | File                    |
| :-------             | :----                   |
| `Roda`               | `lib/roda.rb` (remains) |
| `Roda::RodaRequest`  | `lib/roda/request.rb`   |
| `Roda::RodaResponse` | `lib/roda/response.rb`  |
| `Roda::RodaPlugins`  | `lib/roda/plugins.rb`   |
| `Roda::RodaCache`    | `lib/roda/cache.rb`     |

I also moved the `Roda::RodaPlugins::Base::*` methods modules into the core classes themselves:

| Original                                        | New                                   |
| :--------                                       | :----------------                     |
| `Roda::RodaPlugins::Base::ClassMethods`         | `Roda::ClassMethods`                  |
| `Roda::RodaPlugins::Base::InstanceMethods`      | `Roda::InstanceMethods`               |
| `Roda::RodaPlugins::Base::RequestClassMethods`  | `Roda::RodaRequest::ClassMethods`     |
| `Roda::RodaPlugins::Base::RequestMethods`       | `Roda::RodaRequest::InstanceMethods`  |
| `Roda::RodaPlugins::Base::ResponseClassMethods` | `Roda::RodaResponse::ClassMethods`    |
| `Roda::RodaPlugins::Base::ResponseMethods`      | `Roda::RodaResponse::InstanceMethods` |

This means the base functionality is not treated like a plugin anymore, but by still using modules we continue to allow plugins to call super when overriding base methods.

I kept the original `Roda::Plugins::Base::*` constants as aliases for backwards compatibility.

### Notes

In Shrine I started the same way, that the base functionality was in `lib/shrine.rb`. When a contributor [proposed to split it up](https://github.com/shrinerb/shrine/pull/320), at first I was reluctant. But when we agreed on the new module organization, I started to see the benefits, and over the last year I've felt that code navigation was easier.

I would of course fully respect if you don't feel the same way and don't accept the PR, I just wanted to make the actual code changes to make the proposal concrete 😃

### CODE REVIEW

**Comment by jeremyevans** [comment]
Like you, I'm a bit reluctant to make this change.  My main concern with doing so is that it makes historical analysis/`git diff|blame` harder to use. However, I am willing to consider it.  Can you post on the Google group and get some community feedback for this?

In regards to the patch itself, we could keep using `Base` as a plugin, that change seems separate from splitting the file into multiple files. Is there a reason you want to make that change (even if the files were not split)?

**Comment by janko** [comment]
> However, I am willing to consider it. Can you post on the Google group and get some community feedback for this?

Thanks, I've [posted](https://groups.google.com/forum/#!topic/ruby-roda/jpSvHBqskGs) it on the Google group.

> Is there a reason you want to make that change (even if the files were not split)?

I preferred this change together with the split, because it makes `roda/request.rb` and `roda/response.rb` files self-contained, meaning that when we require those files, the corresponding classes are already fully defined (as opposed to being defined only after the `Roda.plugin` call in `roda.rb`). This makes sense to me from the design perspective, and I think it also lowers the barrier entry for the reader, as they don't have to understand the plugin system to read the base functionality.

But if you prefer, I can revert to `Base` and have the files like this:

```rb
# lib/roda/request.rb
class Roda
  class RodaRequest < ::Rack::Request ... end

  module RodaPlugins
    module Base
      module RequestClassMethods ... end
      module RequestMethods ... end
    end
  end
end
```

```rb
# lib/roda/response.rb
class Roda
  class RodaResponse ... end

  module RodaPlugins
    module Base
      module ResponseClassMethods ... end
      module ResponseMethods ... end
    end
  end
end
```

```rb
# lib/roda.rb
# ...
require_relative "roda/request"
require_relative "roda/response"
# ....
class Roda
  module RodaPlugins
    module Base
      module ClassMethods ... end
      module InstanceMethods ... end
    end
  end

  extend RodaPlugins::Base::ClassMethods
  plugin RodaPlugins::Base
end
```

**Comment by jeremyevans** [comment]
After reviewing the community feedback, I've accepted splitting `roda.rb` into multiple files.  However, I'd like to keep using the Base plugin for now.  Can you update the PR for that?

**Comment by janko** [comment]
@jeremyevans Done ✅

**Comment by jeremyevans** [comment]
Looks good, thanks for your work on this!

**Pull request merged**
