### PR TITLE
Added ability to call content_for multiple times with the same key.

### PR DESCRIPTION
**Pull request by evanleck**
When using nested partials this can be really helpful. I personally use it to put JavaScripts down at the end of the <body>

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch! Unfortunately, the problem with this is it breaks backwards compatibility, as calling content_for multiple times currently overwrites the value instead of appending to it.

I think there are a few ways to handle this.  One is a content_for plugin `:append` option, which would enable the behavior you want.

Another approach would be a separate method (e.g. `append_content_for`) that would append.

Another approach would be adding an options hash to the `content_for` method and supporting a `:append` option.

I think either the plugin option or method option approaches would be best.  The method option approach is more flexible, so we may want to do that.  In Roda 3, we could make appending the default behavior.

What are your thoughts about this?

**Comment by evanleck** [comment]
Ah yeah, that makes sense. I hadn't really considered overwriting a desired outcome but it makes sense for backward compatibility.

I think some kind of option passed either to the method call or the plugin call would make the most sense. For some reason making a whole separate method seems like we'd be duplicating really similar functionality.

Would something like this work for you?

```ruby
plugin :content_for, append: true
```

Would adding it as an option to the `content_for` method call itself be useful? It might make the method signature a little goofy though, huh?

What do you think?

**Comment by jeremyevans** [comment]
That's the plugin option approach.  It makes the method calling simpler, but at the cost of flexibility, since you can no longer replace the content, you can only append to it.  Adding it as a method calling option gives flexibility, but at the cost of making things more verbose.

Let's start with the plugin option and keep things simple to use.  If someone asks for the flexibility of the method option later, we can always add it at that point.

**Comment by evanleck** [comment]
Alright, I've pushed an update with the `:append => true` option added.

**Comment by jeremyevans** [comment]
This looks good.  I'll try to test and merge later today.  Thanks!

**Comment by evanleck** [comment]
Awesome, thank you!

**Pull request merged**
