### PR TITLE
Site Redesign

### PR DESCRIPTION
**Pull request by activestylus**
So, aside from redesigning the site, I've added 2 helpers to your make_www script.

1. The `data` helper
Accesses content inside YAML files. I've found this separation makes templates cleaner and easier to update/style, especially when you've got lists or groups of items.

Example: `data(:home, :top_features)` will look inside the data folder at home.yml and access the content for top_features. For deeper nesting, you can do `data(:home, :top_features, :simplicity)`. It's basically syntactic sugar to avoid all the extra punctuation/ceremony of data["home"]["top_features"], plus I like how symbols pop out in my text editor. Makes it easier to see where dynamic content is.

2. The embed helper
Converts a youtube link into an html embed. Wouldn't be hard to get vimeo and other video services in there, but for now I kept it basic.

IMPORTANT NOTE:

There's a sitemap inside site.yml, accessible as such `data(:site, :pages)`. Anytime you add a new page to the site, you will need to add it to this list (sans the .erb extension) or the script won't compile. I'm using this strategy to provide active context for navigation, and also keep the most important SEO content in one place.

There are also a number of SEO improvements, which should significantly boost your rank and visibility on google.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for all of your hard work on this!  I really like the new design.  I'll probably modify the internals a bit as I don't want to store the data in yaml, and there are a few other minor changes necessary (e.g. relative links instead of absolute links so the pages work correctly if accessed from the file system or served from a subdirectory).  However, I can take care of all of that.

**Comment by activestylus** [comment]
Glad you dig it! I sincerely hope this gives Roda the exposure it deserves. Looking forward to seeing it go live so ping me when it's ready :)

**Comment by jeremyevans** [comment]
I committed this as b179dd23fff1563cdfd71e25a959c9f30bbdad6e.  I normally would use a merge commit, but I didn't want the `.DS_Store` files in the repo history. I reverted the changes to the mode of some files from 644 to 755.  I changed the links to be relative links instead of absolute links (so you can view the site directly from the file system), and removed the use of yaml files as I didn't want the extra layer of indirection.

I made some other minor changes, such as including the most popular frameworks in the benchmarks and some minor content modifications.

Please review and let me know if you think any additional changes should be made.  If not, I'll try to switch the official site to the new design tomorrow.

**Comment by activestylus** [comment]
Late on this side of the pond. Will review tomorrow and provide feedback. Cheers!

**Pull request closed without merging**
