### PR TITLE
Add plugin to append missing trailing slashes

### PR DESCRIPTION
**Pull request by kenaniah**
The add_trailing_slashes plugin appends and redirects when a trailing slash is missing when the path matches a rack app. This provides canonical URL redirection wherever rack apps are loaded.

### CODE REVIEW

**Comment by jeremyevans** [comment]
I'm OK with the basic idea of the plugin, but we don't accept new plugins/features without tests.

Also, in terms in implementation, using a redirect isn't transparent (POST requests, APIs), so you'd probably just want to modify PATH_INFO to append a slash.  Maybe:

```ruby
def run(app)
  env['PATH_INFO'] += '/' if remaining_path.empty?
  super
end
```

I think we may want to rename the plugin.  For one, add_trailing_slashes sounds like it might add multiple trailing slashes to a single request, and it isn't specific to r.run.  Maybe `run_append_slash`?  I'm open to suggestions.

**Comment by jeremyevans** [comment]
I don't have a problem with redirects being optional behavior, as long as it is not the default.

Is there a reason you are using `is` instead of `if remaining_path.empty?` as I used?  Forcing people to use the `pass` plugin for this seems like overkill.  

Note that this still needs tests before it can be accepted.

**Comment by kenaniah** [comment]
Currently working on the tests. The reason I'm using pass is because it would internally append a `/` to all requests unless I directly matched the "root" path of the sub app using `is`.  Attempting to parse `@remaining_path` appeared to be complex and error prone, as it may have tightly-coupled this component with specific routing implementation details.

**Comment by kenaniah** [comment]
Tests have been added. Open to any additional feedback you may have.

**Comment by jeremyevans** [comment]
All `is` does with no arguments is check if `remaining_path` is empty, and yield if so, so I'm not sure what parsing you would have to do to it.

The tests look good.  Can you try using the code I listed earlier?  I don't think anything will break.

**Comment by kenaniah** [comment]
Good to know! I refactored to remove the dependency on `pass` using `remaining_path.empty?`, but the `env['PATH_INFO'] += '/'` does not yield the results expected.

**Comment by jeremyevans** [comment]
You didn't do `env['PATH_INFO'] += '/'`, you did `@remaining_path = @remaining_path + '/'`, which is not the same thing.  When using `run`, only `env` matters, since that is what is given as an argument to the rack app.

**Comment by kenaniah** [comment]
Feel free to try and see for yourself that using `env['PATH_INFO'] += '/'` is not equivalent. There are two assertions in the suite that fail when using it instead of `@remaining_path`. Those assertions are the ones that check that a trailing slash was properly appended to the remaining path for internal routing purposes, and thus breaks the intended functionality of this plugin. 

Is there a downside to using `@remaing_path`?

**Comment by jeremyevans** [comment]
Sorry for the bad information earlier.  You are correct that updating `env['PATH_INFO']` is not sufficient. This is because `run` updates `env['PATH_INFO']` using `remaining_path`.  However, if you don't update `env['PATH_INFO']` as well, looking at the code for `run`, I'm guessing `env['SCRIPT_NAME']` is incorrect in the sub app.  I'll try to fix that when I test and merge tomorrow.

**Comment by jeremyevans** [comment]
Looks like you don't need to modify `env['PATH_INFO']` for things to work correctly, sort of by accident, because a `String#chomp` call with the empty string operates the same as `String#chomp` call where the receiver doesn't end with the argument.  This should be merged shortly, I just need to do some final tests.

**Pull request merged**
